### ISSUE TITLE
insert nbviewer badge when making demos in Windows platform

### ISSUE THREAD

**Issue by DeathGodBXX** [johnnychen94/DemoCards.jl#46]
using DemoCards
template,theme = cardtheme("grid")
MyDemoCards,postprocess_cb = makedemos("democards", template)

makedocs(;
    modules = [MyTestPkg],
    authors = "DeathGodBXX <xxxx> and contributors",
    repo = "https://github.com/DeathGodBXX/MyTestPkg.jl/blob/{commit}{path}#L{line}",
    sitename = "MyTestPkg.jl",
    format = Documenter.HTML(;
          prettyurls = get(ENV, "CI", "false") == "true",
          canonical = "https://DeathGodBXX.github.io/MyTestPkg.jl",
          edit_link = "master",
          assets = String[theme],
    ),
    pages = [
        "Home" => "index.md",
        "MyDemoCards" => MyDemoCards,
    ],
)

postprocess_cb()

demo2.jl has generated *.md ,*.ipynb,*.html ,but don't has nbviewer,what should I do in make.jl ?

**Comment by johnnychen94** [comment]
Nbviewer is only a link to the ipynb file. Because you can not open the nbviewer for a local ipynb file, which gives you a 404, so DemoCards has made a decision to directly point you to the local file _if the documentation is deployed in a local environment_. 

If it is deployed in a CI environment, then it is a nbviewer URL to the specific ipynb file.  For example, if you click the "show nbviwer" badge in [Image-Compression-using-SVD](https://juliaimages.org/latest/democards/examples/color_channels/color_separations_svd/#Image-Compression-using-SVD-1), then you'll get a URL 
`https://nbviewer.jupyter.org/github/JuliaImages/juliaimages.github.io/blob/master/dev/democards/examples/color_channels/color_separations_svd.ipynb`, which is a nbviwer URL to the generated ipynb file.

**Comment by johnnychen94** [comment]
Oh, I think it is another issue here.

That I skipped to add nbviewer badge for Windows platforms:

https://github.com/johnnychen94/DemoCards.jl/blob/master/src/types/julia.jl#L134-L151

**Comment by DeathGodBXX** [comment]
Yes! I just use atom for windows platforms.Maybe I should run this procedure on Ubuntu19.10.
