### ISSUE TITLE
How to customize default css style?

### ISSUE THREAD

**Issue by findmyway** [johnnychen94/DemoCards.jl#90]
For example, I'd like to change the following line:

https://github.com/johnnychen94/DemoCards.jl/blob/e56c25843ea5584e62c9272a0a65146e47dc31f0/src/Themes/grid/style.css#L36

to `display:inline`.

**Comment by johnnychen94** [comment]
I've not tried it, but I think it's doable to:

1. copy and modify your local version of [style.css](https://github.com/johnnychen94/DemoCards.jl/blob/master/src/Themes/grid/style.css), maybe as `democard_style.css`
2. instead of pass `experiment_assets`, pass your own version of it.

Take [ReinforceLearning make.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/99328646eb0b73afd0df138c55130eaf4cef7bc8/docs/make.jl#L15-L21) as an example:

```diff
experiments, postprocess_cb, experiments_assets = makedemos("experiments")
assets = [
    "assets/favicon.ico",
    "assets/custom.css",
-     experiments_assets]
+     "path/to/my/democards_style.css"]
```

One caveat of this approach is that you have to stick to the chosen theme layout and HTML structure, otherwise it might not work. Say you want to provide your own version of `style.css` for grid theme, you need to follow the https://github.com/johnnychen94/DemoCards.jl/blob/master/src/Themes/grid/grid.jl structure.

**Comment by findmyway** [comment]
I see. Thanks!
